sudo: required
language: generic
services:
  - docker
  
before_install:
  - docker build -t manadaym/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true manadaym/docker-react npm run test
